In [1]:
! pip install psycopg2

Requirement already satisfied: psycopg2 in c:\users\elizabeth\anaconda3\lib\site-packages (2.9.5)

In [1]:
import pandas as pd
import numpy as np

# **Read in the LA inspection CSV**

In [2]:
# Read in LA inspection data CSV
la_data = "Resources/LA Restaurant & Market Health Data/restaurant-and-market-health-inspections.csv"
la_data_df = pd.read_csv(la_data)
la_data_df

,serial_number,activity_date,facility_name,score,grade,service_code,service_description,employee_id,facility_address,facility_city,facility_id,facility_state,facility_zip,owner_id,owner_name,pe_description,program_element_pe,program_name,program_status,record_id
0,DAJ00E07B,2017-12-29T00:00:00.000,HABITAT COFFEE SHOP,95,A,1,ROUTINE INSPECTION,EE0000923,3708 N EAGLE ROCK BLVD,LOS ANGELES,FA0170465,CA,90065,OW0178123,GLASSELL COFFEE SHOP LLC,RESTAURANT (0-30) SEATS MODERATE RISK,1631,HABITAT COFFEE SHOP,ACTIVE,PR0160774
1,DAQOKRFZB,2017-12-29T00:00:00.000,REILLY'S,92,A,1,ROUTINE INSPECTION,EE0000633,100 WORLD WAY # 120,LOS ANGELES,FA0244690,CA,90045,OW0208441,"AREAS SKYVIEW LAX JV, LLC",RESTAURANT (0-30) SEATS MODERATE RISK,1631,REILLY'S,ACTIVE,PR0193026
2,DASJI4LUR,2017-12-29T00:00:00.000,STREET CHURROS,93,A,1,ROUTINE INSPECTION,EE0000835,6801 HOLLYWOOD BLVD # 253,LOS ANGELES,FA0224109,CA,90028,OW0228670,"STREETCHURROS, INC",RESTAURANT (0-30) SEATS LOW RISK,1630,STREET CHURROS,ACTIVE,PR0179282
3,DA40LU5AT,2017-12-29T00:00:00.000,TRINITI ECHO PARK,94,A,1,ROUTINE INSPECTION,EE0000923,1814 W SUNSET BLVD,LOS ANGELES,FA0252528,CA,90026-3227,OW0246287,AMERICAN HOSPITALITY,RESTAURANT (0-30) SEATS MODERATE RISK,1631,TRINITI ECHO PARK,ACTIVE,PR0201836
4,DAXV2RMYC,2017-12-29T00:00:00.000,POLLEN,94,A,1,ROUTINE INSPECTION,EE0000923,2100 ECHO PARK AVE,LOS ANGELES,FA0252789,CA,90026,OW0246479,"POLLEN AND PASTRY , LLC",RESTAURANT (0-30) SEATS MODERATE RISK,1631,POLLEN,ACTIVE,PR0202148
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67568,DAZZ4BFUD,2018-06-15T00:00:00.000,RAMEN MARUYA,94,A,1,ROUTINE INSPECTION,EE0000360,104 JAPANESE VILLAGE PLZ MALL,LOS ANGELES,FA0159703,CA,90012,OW0124708,RAMEN MARUYA INC,RESTAURANT (31-60) SEATS HIGH RISK,1635,RAMEN MARUYA,ACTIVE,PR0147764
67569,DAZZ4TRBY,2018-05-16T00:00:00.000,KANG WON DO,96,A,1,ROUTINE INSPECTION,EE0000723,4050 W WASHINGTON BLVD,LOS ANGELES,FA0137540,CA,90018,OW0100601,KANG WON DO CORPORATION,"FOOD MKT RETAIL (2,000+ SF) LOW RISK",1613,KANG WON DO,ACTIVE,PR0121641
67570,DAZZ9YUS4,2018-04-20T00:00:00.000,OASIS MARKET,91,A,1,ROUTINE INSPECTION,EE0000594,4312 WALL ST,LOS ANGELES,FA0170167,CA,90011,OW0178002,"MCLELLAN INVESTMENTS, LLC","FOOD MKT RETAIL (2,000+ SF) HIGH RISK",1615,OASIS MARKET,ACTIVE,PR0160629
67571,DAZZJBQUO,2018-04-17T00:00:00.000,TEN TEN YU RAMEN,95,A,1,ROUTINE INSPECTION,EE0000375,2012 SAWTELLE BLVD,LOS ANGELES,FA0225467,CA,90025,OW0229730,"WAO, INC.",RESTAURANT (31-60) SEATS HIGH RISK,1635,TEN TEN YU RAMEN,ACTIVE,PR0180788
67572,DAZZL6GP3,2018-06-07T00:00:00.000,SUPERIOR GROCERS #113,97,A,1,ROUTINE INSPECTION,EE0000557,3600 E CESAR E CHAVEZ AVE,LOS ANGELES,FA0049848,CA,90063,OW0034460,"SUPER CENTER CONCEPTS, INC",RESTAURANT (0-30) SEATS MODERATE RISK,1631,SUPERIOR GROCERS #113 TORTIL,ACTIVE,PR0019416

# **Read in the LA violation CSV**

In [3]:
# Read in LA violation data CSV
la_violation_data = "Resources/LA Restaurant & Market Health Data/restaurant-and-market-health-violations.csv"
la_violation_data_df = pd.read_csv(la_violation_data)
la_violation_data_df

,serial_number,activity_date,facility_name,violation_code,violation_description,violation_status,points,grade,facility_address,facility_city,...,owner_name,pe_description,program_element_pe,program_name,program_status,record_id,score,service_code,service_description,row_id
0,DA08R0TCU,2018-03-30T00:00:00.000,KRUANG TEDD,F030,# 30. Food properly stored; food storage conta...,OUT OF COMPLIANCE,1,A,5151 HOLLYWOOD BLVD,LOS ANGELES,...,5151 HOLLYWOOD LLC,RESTAURANT (31-60) SEATS HIGH RISK,1635,KRUANG TEDD,ACTIVE,PR0031205,92,1,ROUTINE INSPECTION,DA08R0TCUF030
1,DA08R0TCU,2018-03-30T00:00:00.000,KRUANG TEDD,F027,# 27. Food separated and protected,OUT OF COMPLIANCE,1,A,5151 HOLLYWOOD BLVD,LOS ANGELES,...,5151 HOLLYWOOD LLC,RESTAURANT (31-60) SEATS HIGH RISK,1635,KRUANG TEDD,ACTIVE,PR0031205,92,1,ROUTINE INSPECTION,DA08R0TCUF027
2,DA08R0TCU,2018-03-30T00:00:00.000,KRUANG TEDD,F035,# 35. Equipment/Utensils - approved; installed...,OUT OF COMPLIANCE,1,A,5151 HOLLYWOOD BLVD,LOS ANGELES,...,5151 HOLLYWOOD LLC,RESTAURANT (31-60) SEATS HIGH RISK,1635,KRUANG TEDD,ACTIVE,PR0031205,92,1,ROUTINE INSPECTION,DA08R0TCUF035
3,DA08R0TCU,2018-03-30T00:00:00.000,KRUANG TEDD,F033,# 33. Nonfood-contact surfaces clean and in go...,OUT OF COMPLIANCE,1,A,5151 HOLLYWOOD BLVD,LOS ANGELES,...,5151 HOLLYWOOD LLC,RESTAURANT (31-60) SEATS HIGH RISK,1635,KRUANG TEDD,ACTIVE,PR0031205,92,1,ROUTINE INSPECTION,DA08R0TCUF033
4,DA08R0TCU,2018-03-30T00:00:00.000,KRUANG TEDD,F029,"# 29. Toxic substances properly identified, st...",OUT OF COMPLIANCE,1,A,5151 HOLLYWOOD BLVD,LOS ANGELES,...,5151 HOLLYWOOD LLC,RESTAURANT (31-60) SEATS HIGH RISK,1635,KRUANG TEDD,ACTIVE,PR0031205,92,1,ROUTINE INSPECTION,DA08R0TCUF029
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313670,DAZZJBQUO,2018-04-17T00:00:00.000,TEN TEN YU RAMEN,F009,# 09. Proper cooling methods,OUT OF COMPLIANCE,2,A,2012 SAWTELLE BLVD,LOS ANGELES,...,"WAO, INC.",RESTAURANT (31-60) SEATS HIGH RISK,1635,TEN TEN YU RAMEN,ACTIVE,PR0180788,95,1,ROUTINE INSPECTION,DAZZJBQUOF009
313671,DAZZJBQUO,2018-04-17T00:00:00.000,TEN TEN YU RAMEN,F027,# 27. Food separated and protected,OUT OF COMPLIANCE,1,A,2012 SAWTELLE BLVD,LOS ANGELES,...,"WAO, INC.",RESTAURANT (31-60) SEATS HIGH RISK,1635,TEN TEN YU RAMEN,ACTIVE,PR0180788,95,1,ROUTINE INSPECTION,DAZZJBQUOF027
313672,DAZZL6GP3,2018-06-07T00:00:00.000,SUPERIOR GROCERS #113,F033,# 33. Nonfood-contact surfaces clean and in go...,OUT OF COMPLIANCE,1,A,3600 E CESAR E CHAVEZ AVE,LOS ANGELES,...,"SUPER CENTER CONCEPTS, INC",RESTAURANT (0-30) SEATS MODERATE RISK,1631,SUPERIOR GROCERS #113 TORTIL,ACTIVE,PR0019416,97,1,ROUTINE INSPECTION,DAZZL6GP3F033
313673,DAZZL6GP3,2018-06-07T00:00:00.000,SUPERIOR GROCERS #113,F043,# 43. Premises; personal/cleaning items; vermi...,OUT OF COMPLIANCE,1,A,3600 E CESAR E CHAVEZ AVE,LOS ANGELES,...,"SUPER CENTER CONCEPTS, INC",RESTAURANT (0-30) SEATS MODERATE RISK,1631,SUPERIOR GROCERS #113 TORTIL,ACTIVE,PR0019416,97,1,ROUTINE INSPECTION,DAZZL6GP3F043
313674,DAZZL6GP3,2018-06-07T00:00:00.000,SUPERIOR GROCERS #113,F044,"# 44. Floors, walls and ceilings: properly bui...",OUT OF COMPLIANCE,1,A,3600 E CESAR E CHAVEZ AVE,LOS ANGELES,...,"SUPER CENTER CONCEPTS, INC",RESTAURANT (0-30) SEATS MODERATE RISK,1631,SUPERIOR GROCERS #113 TORTIL,ACTIVE,PR0019416,97,1,ROUTINE INSPECTION,DAZZL6GP3F044

In [4]:
la_violation_data_df.columns

Index(['serial_number', 'activity_date', 'facility_name', 'violation_code',
       'violation_description', 'violation_status', 'points', 'grade',
       'facility_address', 'facility_city', 'facility_id', 'facility_state',
       'facility_zip', 'employee_id', 'owner_id', 'owner_name',
       'pe_description', 'program_element_pe', 'program_name',
       'program_status', 'record_id', 'score', 'service_code',
       'service_description', 'row_id'],
      dtype='object')

#  **Read in the Chicago inspection CSV**

In [5]:
# Read in Chicago inspection data CSV
chicago_data = "Resources/food-inspections.csv"
chicago_data_df = pd.read_csv(chicago_data)
chicago_data_df

,Inspection ID,DBA Name,AKA Name,License #,Facility Type,Risk,Address,City,State,Zip,...,Results,Violations,Latitude,Longitude,Location,Historical Wards 2003-2015,Zip Codes,Community Areas,Census Tracts,Wards
0,2352683,CHIPOTLE MEXICAN GRILL,CHIPOTLE MEXICAN GRILL,2670642.0,Restaurant,Risk 1 (High),1025 W ADDISON ST,CHICAGO,IL,60613.0,...,Pass w/ Conditions,"3. MANAGEMENT, FOOD EMPLOYEE AND CONDITIONAL E...",41.947118,-87.655381,"{'latitude': '-87.6553811622124', 'longitude':...",NaN,NaN,NaN,NaN,NaN
1,2352734,CHILI'S T-I,CHILI'S (T1-B14),34169.0,Restaurant,Risk 1 (High),11601 W TOUHY AVE,CHICAGO,IL,60666.0,...,Pass,10. ADEQUATE HANDWASHING SINKS PROPERLY SUPPLI...,42.008536,-87.914428,"{'latitude': '-87.91442843927047', 'longitude'...",NaN,NaN,NaN,NaN,NaN
2,2352713,NICK'S FIRE GRILL STEAK & LEMONADE INC.,NICK'S FIRE GRILL STEAK & LEMONADE INC.,2699090.0,NaN,Risk 1 (High),2900 W 63RD ST,CHICAGO,IL,60629.0,...,Not Ready,NaN,41.779190,-87.695892,"{'latitude': '-87.69589237398256', 'longitude'...",NaN,NaN,NaN,NaN,NaN
3,2352701,TAQUERIA BLUE LINE INC.,NaN,2703436.0,Restaurant,Risk 1 (High),3401 W BELMONT AVE,CHICAGO,IL,60618.0,...,Pass w/ Conditions,"3. MANAGEMENT, FOOD EMPLOYEE AND CONDITIONAL E...",41.939168,-87.712546,"{'latitude': '-87.71254599117191', 'longitude'...",NaN,NaN,NaN,NaN,NaN
4,2352727,PORTAGE PARK DAY NURSERY,MOSAIC EARLY CHILDHOOD ACADEMY,2215815.0,Children's Services Facility,Risk 1 (High),5332-5334 W ADDISON ST,CHICAGO,IL,60641.0,...,Pass,NaN,41.946065,-87.760722,"{'latitude': '-87.76072227616888', 'longitude'...",NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196820,52234,Cafe 608,Cafe 608,2013328.0,Restaurant,Risk 1 (High),608 W BARRY AVE,CHICAGO,IL,60657.0,...,Pass,NaN,41.938007,-87.644755,"{'latitude': '-87.6447545707008', 'longitude':...",NaN,NaN,NaN,NaN,NaN
196821,104236,TEMPO CAFE,TEMPO CAFE,80916.0,Restaurant,Risk 1 (High),6 E CHESTNUT ST,CHICAGO,IL,60611.0,...,Fail,18. NO EVIDENCE OF RODENT OR INSECT OUTER OPEN...,41.898431,-87.628009,"{'latitude': '-87.6280091630558', 'longitude':...",NaN,NaN,NaN,NaN,NaN
196822,67732,WOLCOTT'S,TROQUET,1992039.0,Restaurant,Risk 1 (High),1834 W MONTROSE AVE,CHICAGO,IL,60613.0,...,Pass,NaN,41.961606,-87.675967,"{'latitude': '-87.67596676683779', 'longitude'...",NaN,NaN,NaN,NaN,NaN
196823,70269,mr.daniel's,mr.daniel's,1899292.0,Restaurant,Risk 1 (High),5645 W BELMONT AVE,CHICAGO,IL,60634.0,...,Pass,NaN,41.938443,-87.768318,"{'latitude': '-87.76831838068422', 'longitude'...",NaN,NaN,NaN,NaN,NaN
196824,67738,MICHAEL'S ON MAIN CAFE,MICHAEL'S ON MAIN CAFE,2008948.0,Restaurant,Risk 1 (High),8750 W BRYN WAWR AVE,CHICAGO,IL,60631.0,...,Fail,18. NO EVIDENCE OF RODENT OR INSECT OUTER OPEN...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
chicago_data_df.columns

Index(['Inspection ID', 'DBA Name', 'AKA Name', 'License #', 'Facility Type',
       'Risk', 'Address', 'City', 'State', 'Zip', 'Inspection Date',
       'Inspection Type', 'Results', 'Violations', 'Latitude', 'Longitude',
       'Location', 'Historical Wards 2003-2015', 'Zip Codes',
       'Community Areas', 'Census Tracts', 'Wards'],
      dtype='object')

#  **Clean the LA violation CSV**

In [7]:
#clean LA violation data
# Create Copy of original CSV
laviolationdatadf = la_violation_data_df.copy()

# Find any duplicated rows in Fast Food df
laviolationdatadf = laviolationdatadf.drop_duplicates()

## drop NaN values
laviolationdatadf = laviolationdatadf.dropna() # removes 175 rows

# remove hours and seconds from the date
laviolationdatadf['activity_date'] = pd.to_datetime(laviolationdatadf['activity_date'])

# remove columns
laviolationdatadf = laviolationdatadf[['serial_number', 'activity_date', 'facility_name', 'violation_code', 
                                       'violation_description', 'violation_status', 'facility_id']]


laviolationdatadf

,serial_number,activity_date,facility_name,violation_code,violation_description,violation_status,facility_id
0,DA08R0TCU,2018-03-30,KRUANG TEDD,F030,# 30. Food properly stored; food storage conta...,OUT OF COMPLIANCE,FA0064949
1,DA08R0TCU,2018-03-30,KRUANG TEDD,F027,# 27. Food separated and protected,OUT OF COMPLIANCE,FA0064949
2,DA08R0TCU,2018-03-30,KRUANG TEDD,F035,# 35. Equipment/Utensils - approved; installed...,OUT OF COMPLIANCE,FA0064949
3,DA08R0TCU,2018-03-30,KRUANG TEDD,F033,# 33. Nonfood-contact surfaces clean and in go...,OUT OF COMPLIANCE,FA0064949
4,DA08R0TCU,2018-03-30,KRUANG TEDD,F029,"# 29. Toxic substances properly identified, st...",OUT OF COMPLIANCE,FA0064949
...,...,...,...,...,...,...,...
313670,DAZZJBQUO,2018-04-17,TEN TEN YU RAMEN,F009,# 09. Proper cooling methods,OUT OF COMPLIANCE,FA0225467
313671,DAZZJBQUO,2018-04-17,TEN TEN YU RAMEN,F027,# 27. Food separated and protected,OUT OF COMPLIANCE,FA0225467
313672,DAZZL6GP3,2018-06-07,SUPERIOR GROCERS #113,F033,# 33. Nonfood-contact surfaces clean and in go...,OUT OF COMPLIANCE,FA0049848
313673,DAZZL6GP3,2018-06-07,SUPERIOR GROCERS #113,F043,# 43. Premises; personal/cleaning items; vermi...,OUT OF COMPLIANCE,FA0049848
313674,DAZZL6GP3,2018-06-07,SUPERIOR GROCERS #113,F044,"# 44. Floors, walls and ceilings: properly bui...",OUT OF COMPLIANCE,FA0049848

# **Clean the LA inspection CSV**

In [8]:
#clean LA inspection data
# Create Copy of original CSV
ladatadf = la_data_df.copy()

# Find any duplicated rows in Fast Food df
ladatadf = ladatadf.drop_duplicates()

## drop NaN values
ladatadf = ladatadf.dropna() # only removes 3 rows

# remove hours and seconds from the date
ladatadf['activity_date'] = pd.to_datetime(ladatadf['activity_date'])

# remove columns
ladatadf = ladatadf[['serial_number', 'activity_date', 'facility_name', 'facility_address', 
                     'facility_city', 'facility_state', 'facility_zip', 'facility_id', 'grade', 
                     'score', 'program_status', 'record_id','service_description']]


ladatadf

,serial_number,activity_date,facility_name,facility_address,facility_city,facility_state,facility_zip,facility_id,grade,score,program_status,record_id,service_description
0,DAJ00E07B,2017-12-29,HABITAT COFFEE SHOP,3708 N EAGLE ROCK BLVD,LOS ANGELES,CA,90065,FA0170465,A,95,ACTIVE,PR0160774,ROUTINE INSPECTION
1,DAQOKRFZB,2017-12-29,REILLY'S,100 WORLD WAY # 120,LOS ANGELES,CA,90045,FA0244690,A,92,ACTIVE,PR0193026,ROUTINE INSPECTION
2,DASJI4LUR,2017-12-29,STREET CHURROS,6801 HOLLYWOOD BLVD # 253,LOS ANGELES,CA,90028,FA0224109,A,93,ACTIVE,PR0179282,ROUTINE INSPECTION
3,DA40LU5AT,2017-12-29,TRINITI ECHO PARK,1814 W SUNSET BLVD,LOS ANGELES,CA,90026-3227,FA0252528,A,94,ACTIVE,PR0201836,ROUTINE INSPECTION
4,DAXV2RMYC,2017-12-29,POLLEN,2100 ECHO PARK AVE,LOS ANGELES,CA,90026,FA0252789,A,94,ACTIVE,PR0202148,ROUTINE INSPECTION
...,...,...,...,...,...,...,...,...,...,...,...,...,...
67568,DAZZ4BFUD,2018-06-15,RAMEN MARUYA,104 JAPANESE VILLAGE PLZ MALL,LOS ANGELES,CA,90012,FA0159703,A,94,ACTIVE,PR0147764,ROUTINE INSPECTION
67569,DAZZ4TRBY,2018-05-16,KANG WON DO,4050 W WASHINGTON BLVD,LOS ANGELES,CA,90018,FA0137540,A,96,ACTIVE,PR0121641,ROUTINE INSPECTION
67570,DAZZ9YUS4,2018-04-20,OASIS MARKET,4312 WALL ST,LOS ANGELES,CA,90011,FA0170167,A,91,ACTIVE,PR0160629,ROUTINE INSPECTION
67571,DAZZJBQUO,2018-04-17,TEN TEN YU RAMEN,2012 SAWTELLE BLVD,LOS ANGELES,CA,90025,FA0225467,A,95,ACTIVE,PR0180788,ROUTINE INSPECTION
67572,DAZZL6GP3,2018-06-07,SUPERIOR GROCERS #113,3600 E CESAR E CHAVEZ AVE,LOS ANGELES,CA,90063,FA0049848,A,97,ACTIVE,PR0019416,ROUTINE INSPECTION

# **Clean the Chicago inspection CSV**

In [9]:
#clean chicago data
# Create Copy of original CSV
chicagodatadf = chicago_data_df.copy()

# Find any duplicated rows in chicago df
chicagodatadf = chicagodatadf.drop_duplicates()

## drop NaN values but we might want to keep them because they exist in the violations column
# chicagodatadf = chicagodatadf.dropna()
# chicagodatadf = chicagodatadf.replace(np.nan, '', regex=True) ## makes the NaN values blank

# fix zip code and license number format
chicagodatadf['Zip'] = chicagodatadf['Zip'].fillna(0)
chicagodatadf['Zip'] = chicagodatadf['Zip'].astype(int)
chicagodatadf['License #'] = chicagodatadf['License #'].fillna(0)
chicagodatadf['License #'] = chicagodatadf['License #'].astype(int)


# remove columns
chicagodatadf = chicagodatadf[['Inspection ID', 'Inspection Date', 'DBA Name', 'License #', 'Address',
                               'City', 'State', 'Zip', 'Latitude',
                             'Longitude', 'Inspection Type', 'Results', 'Violations']]

chicagodatadf = chicagodatadf.rename(columns={'Inspection ID': 'inspection_id', 
                                              'Inspection Date' : 'inspection_date', 
                                              'DBA Name' : 'dba_name', 
                                              'License #': 'license_number', 
                                              'Address' : 'address',
                                              'City' : 'city',
                                              'State' : 'state', 
                                              'Zip': 'zip', 
                                              'Latitude' : 'latitude',
                                              'Longitude' : 'longitude', 
                                              'Inspection Type': 'inspection_type', 
                                              'Results' : 'results', 
                                              'Violations' : 'violations'})

# remove hours and seconds from the date
chicagodatadf['inspection_date'] = pd.to_datetime(chicagodatadf['inspection_date'])


chicagodatadf

,inspection_id,inspection_date,dba_name,license_number,address,city,state,zip,latitude,longitude,inspection_type,results,violations
0,2352683,2019-12-04,CHIPOTLE MEXICAN GRILL,2670642,1025 W ADDISON ST,CHICAGO,IL,60613,41.947118,-87.655381,License Re-Inspection,Pass w/ Conditions,"3. MANAGEMENT, FOOD EMPLOYEE AND CONDITIONAL E..."
1,2352734,2019-12-04,CHILI'S T-I,34169,11601 W TOUHY AVE,CHICAGO,IL,60666,42.008536,-87.914428,Canvass,Pass,10. ADEQUATE HANDWASHING SINKS PROPERLY SUPPLI...
2,2352713,2019-12-04,NICK'S FIRE GRILL STEAK & LEMONADE INC.,2699090,2900 W 63RD ST,CHICAGO,IL,60629,41.779190,-87.695892,License,Not Ready,NaN
3,2352701,2019-12-04,TAQUERIA BLUE LINE INC.,2703436,3401 W BELMONT AVE,CHICAGO,IL,60618,41.939168,-87.712546,License,Pass w/ Conditions,"3. MANAGEMENT, FOOD EMPLOYEE AND CONDITIONAL E..."
4,2352727,2019-12-04,PORTAGE PARK DAY NURSERY,2215815,5332-5334 W ADDISON ST,CHICAGO,IL,60641,41.946065,-87.760722,Canvass,Pass,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
196820,52234,2010-01-04,Cafe 608,2013328,608 W BARRY AVE,CHICAGO,IL,60657,41.938007,-87.644755,License Re-Inspection,Pass,NaN
196821,104236,2010-01-04,TEMPO CAFE,80916,6 E CHESTNUT ST,CHICAGO,IL,60611,41.898431,-87.628009,Canvass,Fail,18. NO EVIDENCE OF RODENT OR INSECT OUTER OPEN...
196822,67732,2010-01-04,WOLCOTT'S,1992039,1834 W MONTROSE AVE,CHICAGO,IL,60613,41.961606,-87.675967,License Re-Inspection,Pass,NaN
196823,70269,2010-01-04,mr.daniel's,1899292,5645 W BELMONT AVE,CHICAGO,IL,60634,41.938443,-87.768318,License Re-Inspection,Pass,NaN
196824,67738,2010-01-04,MICHAEL'S ON MAIN CAFE,2008948,8750 W BRYN WAWR AVE,CHICAGO,IL,60631,NaN,NaN,License,Fail,18. NO EVIDENCE OF RODENT OR INSECT OUTER OPEN...

# **Export all dataframes to CSVs**

In [10]:
# # Save chicago CSV
# chicagodatadf.to_csv("Output/chicago_data_cleaned.csv")

# # Save la inspection DF
# ladatadf.to_csv("Output/la_inspection_data_cleaned.csv")

# # Save la inspection DF
# laviolationdatadf.to_csv("Output/la_violation_data_cleaned.csv")

# **Connect to local database**

In [14]:
from sqlalchemy import create_engine

In [17]:
protocol = 'postgresql'
username = 'postgres'
password = 'vineyard'
host = 'localhost'
port = 5432
database_name = 'inspections_db'
rds_connection_string = f'{protocol}://{username}:{password}@{host}:{port}/{database_name}'
engine = create_engine(rds_connection_string)

# **Check for tables**

In [18]:
 engine.table_names()

C:\Users\Elizabeth\AppData\Local\Temp\ipykernel_20156\1612904836.py:1: SADeprecationWarning: The Engine.table_names() method is deprecated and will be removed in a future release.  Please refer to Inspector.get_table_names(). (deprecated since: 1.4)
  engine.table_names()

['chicago_inspection_data', 'la_inspection_data', 'la_violation_data']

# **Load LA inspection data**

In [ ]:
# load LA inspection data
ladatadf.to_sql(name='la_inspection_data', con=engine, if_exists='append', index=False)

# **Load LA violation data**

In [ ]:
# load LA violation data
laviolationdatadf.to_sql(name='la_violation_data', con=engine, if_exists='append', index=False)

# **Load Chicago inspection data**

In [75]:
# load Chicago inspection data
chicagodatadf.to_sql(name='chicago_inspection_data', con=engine, if_exists='append', index=False)