In [1]:
import pandas as pd

# **_CREATE CSV CONNECTIONS_**

In [2]:
# Fast food restaurants across US
fast_food = "Resources/Fast_Food_Restaurants_US.csv"
fast_food_df = pd.read_csv(fast_food)
fast_food_df

,Unnamed: 0,address,categories,city,country,latitude,longitude,name,postalCode,province,websites
0,0,800 N Canal Blvd,American Restaurant and Fast Food Restaurant,Thibodaux,US,29.814697,-90.814742,SONIC Drive In,70301,LA,https://locations.sonicdrivein.com/la/thibodau...
1,1,800 N Canal Blvd,Fast Food Restaurants,Thibodaux,US,29.814697,-90.814742,SONIC Drive In,70301,LA,https://locations.sonicdrivein.com/la/thibodau...
2,2,206 Wears Valley Rd,Fast Food Restaurant,Pigeon Forge,US,35.803788,-83.580553,Taco Bell,37863,TN,"http://www.tacobell.com,https://locations.taco..."
3,3,3652 Parkway,Fast Food,Pigeon Forge,US,35.782339,-83.551408,Arby's,37863,TN,"http://www.arbys.com,https://locations.arbys.c..."
4,4,2118 Mt Zion Parkway,Fast Food Restaurant,Morrow,US,33.562738,-84.321143,Steak 'n Shake,30260,GA,http://www.steaknshake.com/locations/23851-ste...
...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,3460 Robinhood Rd,Fast Food Restaurants,Winston-Salem,US,36.117563,-80.316553,Pizza Hut,27106,NC,http://www.pizzahut.com
9996,9996,3069 Kernersville Rd,Fast Food Restaurants,Winston-Salem,US,36.077718,-80.176748,Pizza Hut,27107,NC,http://www.pizzahut.com
9997,9997,838 S Main St,Fast Food Restaurants,Kernersville,US,36.111015,-80.089165,Pizza Hut,27284,NC,http://www.pizzahut.com
9998,9998,1702 Glendale Dr SW,Fast Food Restaurants,Wilson,US,35.719981,-77.945795,Pizza Hut,27893,NC,http://www.pizzahut.com
9999,9999,1405 W Broad St,Fast Food Restaurants,Elizabethtown,US,34.632778,-78.624615,Pizza Hut,28337,NC,"http://www.pizzahut.com,http://api.citygridmed..."

In [3]:
# 18,000 Vegan & Vegetarian Restaurants in the US
vegan = "Resources/vegetarian_restaurants_US_datafiniti_vegetarian_restaurants_US_datafiniti.csv"
vegan_df = pd.read_csv(vegan)
vegan_df

,address,categories,city,claimed,country,cuisines,dateOpened,dateUpdated,descriptions,facebookPageURL,...,menuURL,name,paymentTypes,phones,postalCode,priceRange,province,sic,twitter,websites
0,2871 Gulf To Bay Blvd,"American, American (new), Clearwater Restauran...",Clearwater,NaN,US,NaN,NaN,2014-02-01T04:41:06Z,"Tags: American (New), American, and Trendy Sta...",NaN,...,NaN,Village Inn Restaurant and Bakery,NaN,7277964988,33759,NaN,FL,8423,NaN,NaN
1,605 W Main St,Caf and Sandwich Place,Louisville,NaN,US,"Vegetarian, Â Delicatessen",NaN,2016-07-23T22:37:24Z,"Atlantic No. 5, Louisville: See 4 unbiased rev...",NaN,...,NaN,Atlantic No. 5,Yes,5028833398,40202,USD 25.00-40.00,KY,NaN,NaN,atlanticno5.com
2,3803 9th St S W,"American, Barbecue, Puyallup Restaurants, Barb...",Puyallup,NaN,US,NaN,NaN,2015-11-19T22:22:31Z,"Description: Famous Dave's is a Barbecue , Am...",NaN,...,NaN,Famous Dave's,NaN,2536040340,98373,USD 10.00 - USD 15.00,WA,5610,NaN,http://famousdaves.com
3,30 S Main St,"Coffee & Tea, Restaurant, Restaurants, Bar, Am...",Oberlin,NaN,US,"Coffee & Tea, Restaurants, American, Â Bar, Â Pu...",NaN,2016-06-20T17:47:10Z,"The Feve, Oberlin: See 170 unbiased reviews of...",NaN,...,/oberlin-oh/mip/the-feve-8940755/menu,The Feve,"mastercard, amex, discover, Yes, visa","[""4407741978"",""4197741978"",""4407753064""]",44074,USD 25.00-40.00,OH,NaN,NaN,http://www.thefeve.com
4,55 Crescent Dr,Sandwich Place and Fast Food Restaurant,Pleasant Hill,yellowpages.com,US,"Take Out Restaurants, Asian Restaurants, Resta...",NaN,2016-07-23T23:55:05Z,"[""https://www.zagat.com/r/yalla-mediterranean-...",NaN,...,/pleasant-hill-ca/mip/yalla-mediterranean-5061...,Quiznos,"master card, visa",9258258644,94523,$,CA,NaN,quiznos,http://www.yallamedi.com/
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18150,879 Smith Ave S,"West St Paul Restaurants, American / Diner / C...",W St Paul,NaN,US,NaN,NaN,2013-09-16T03:41:32Z,"Tags: American, Diner, and Coffeehouse",NaN,...,NaN,The Old Man River Cafe,NaN,6.51E+09,55118,NaN,MN,5610,NaN,NaN
18151,1410 Colonial Life Blvd W,Restaurant,Columbia,NaN,US,"American, ï¿½ï¿½Vegetarian",NaN,2016-04-10T04:24:17Z,"The Melting Pot, Columbia: See 54 unbiased rev...",NaN,...,NaN,The Melting Pot,NaN,8037318500,29210-7665,NaN,SC,NaN,NaN,NaN
18152,9439 Sheridan St,"American, Smoothies & Juices, Hollywood Restau...",Hollywood,NaN,US,NaN,NaN,2013-10-03T01:41:37Z,"Tags: Smoothies & Juice, Vegetarian, and Conve...",NaN,...,NaN,Smoothie King,NaN,9544313411,33024,NaN,FL,0,NaN,http://smoothieking.com
18153,801 N Congress Ave,"[""Restaurants"",""Banquet Halls & Reception Faci...",Boynton Beach,yellowpages.com,US,"[""Mediterranean"",""Restaurants"",""Family Style"",...",NaN,2016-05-31T13:37:09Z,Buca di Beppo serves authentic Italian cuisine...,NaN,...,/boynton-beach-fl/mip/buca-di-beppo-475592729/...,Buca Di Beppo,"amex, cash, discover, all major credit cards, ...","[""5617344558"",""5617330189""]","[""33426""]",$$,FL,5610,NaN,http://www.bucadibeppo.com
18154,1603 Delaware 1,"Rehoboth Beach Restaurants, Pizza / American /...",Rehoboth Beach,NaN,US,NaN,NaN,2013-09-16T04:18:30Z,"Tags: Pizza, American, and Family Style",NaN,...,NaN,Grotto Pizza,NaN,3022273407,19971,NaN,DE,5610,NaN,NaN

# _Fast Food Locations DF_ Cleaning / Transformation

In [4]:
# Create Copy of original CSV
fastfooddf = fast_food_df.copy()

# Find any duplicated rows in Fast Food df
fastfooddf = fastfooddf.drop_duplicates(['name', 'address', 'latitude', 'longitude'])
fastfooddf = fastfooddf.reset_index()

In [5]:
# Remove Unnamed: 0 column as it is another index column
fastfooddf = fastfooddf.drop(columns=["Unnamed: 0"])

# Reorganize columns
fastfooddf = fastfooddf[["name", "categories", "address","city", "postalCode", "province", "country", "latitude", "longitude", "websites"]]

# Rename postalCode to postal_code
fastfooddf.rename(columns={'postalCode':'postal_code'}, inplace=True)
fastfooddf

,name,categories,address,city,postal_code,province,country,latitude,longitude,websites
0,SONIC Drive In,American Restaurant and Fast Food Restaurant,800 N Canal Blvd,Thibodaux,70301,LA,US,29.814697,-90.814742,https://locations.sonicdrivein.com/la/thibodau...
1,Taco Bell,Fast Food Restaurant,206 Wears Valley Rd,Pigeon Forge,37863,TN,US,35.803788,-83.580553,"http://www.tacobell.com,https://locations.taco..."
2,Arby's,Fast Food,3652 Parkway,Pigeon Forge,37863,TN,US,35.782339,-83.551408,"http://www.arbys.com,https://locations.arbys.c..."
3,Steak 'n Shake,Fast Food Restaurant,2118 Mt Zion Parkway,Morrow,30260,GA,US,33.562738,-84.321143,http://www.steaknshake.com/locations/23851-ste...
4,Wendy's,Fast Food Restaurant,9768 Grand River Ave,Detroit,48204,MI,US,42.368823,-83.138251,http://www.wendys.com
...,...,...,...,...,...,...,...,...,...,...
9338,Pizza Hut,Fast Food Restaurants,3460 Robinhood Rd,Winston-Salem,27106,NC,US,36.117563,-80.316553,http://www.pizzahut.com
9339,Pizza Hut,Fast Food Restaurants,3069 Kernersville Rd,Winston-Salem,27107,NC,US,36.077718,-80.176748,http://www.pizzahut.com
9340,Pizza Hut,Fast Food Restaurants,838 S Main St,Kernersville,27284,NC,US,36.111015,-80.089165,http://www.pizzahut.com
9341,Pizza Hut,Fast Food Restaurants,1702 Glendale Dr SW,Wilson,27893,NC,US,35.719981,-77.945795,http://www.pizzahut.com
9342,Pizza Hut,Fast Food Restaurants,1405 W Broad St,Elizabethtown,28337,NC,US,34.632778,-78.624615,"http://www.pizzahut.com,http://api.citygridmed..."

# _Vegan Restaurants DF_ Cleaning / Transformation

In [6]:
# Create Copy of original CSV and listed the columns
vegandf = vegan_df.copy()

# Find any duplicates in Vegan df
vegandf = vegandf.drop_duplicates(['name', 'address', 'lat', 'long'])
vegandf = vegandf.reset_index()

# REMOVE unwanted/unneeded columns by # the wanted columns
vegandf = vegandf.drop(columns=[
#address
#categories
#city
'claimed',
#country
#cuisines
'dateOpened',
'dateUpdated',
'descriptions',
'facebookPageURL',
'features',
'hours',
'images',
'isClosed',
'key',
#lat
'languages',
#long
'menus',
'menuURL',
#name
'paymentTypes',
'phones',
#postalCode
'priceRange',
#province
'sic',
'twitter'
#websites
])

# Reorganize columns
vegandf = vegandf[['name', 'categories', 'cuisines', 'address', 'postalCode', 'city', 'province',
                   'country','lat','long','websites']]

# Rename postalCode to postal_code
vegandf.rename(columns={'postalCode':'postal_code', 'lat':'latitude', 'long':'longitude'}, inplace=True)
vegandf

,name,categories,cuisines,address,postal_code,city,province,country,latitude,longitude,websites
0,Village Inn Restaurant and Bakery,"American, American (new), Clearwater Restauran...",NaN,2871 Gulf To Bay Blvd,33759,Clearwater,FL,US,27.971165,-82.696938,NaN
1,Atlantic No. 5,Caf and Sandwich Place,"Vegetarian, Â Delicatessen",605 W Main St,40202,Louisville,KY,US,38.257020,-85.760013,atlanticno5.com
2,Famous Dave's,"American, Barbecue, Puyallup Restaurants, Barb...",NaN,3803 9th St S W,98373,Puyallup,WA,US,47.154828,-122.303992,http://famousdaves.com
3,The Feve,"Coffee & Tea, Restaurant, Restaurants, Bar, Am...","Coffee & Tea, Restaurants, American, Â Bar, Â Pu...",30 S Main St,44074,Oberlin,OH,US,41.290823,-82.217640,http://www.thefeve.com
4,Quiznos,Sandwich Place and Fast Food Restaurant,"Take Out Restaurants, Asian Restaurants, Resta...",55 Crescent Dr,94523,Pleasant Hill,CA,US,37.945663,-122.061997,http://www.yallamedi.com/
...,...,...,...,...,...,...,...,...,...,...,...
14636,The Old Man River Cafe,"West St Paul Restaurants, American / Diner / C...",NaN,879 Smith Ave S,55118,W St Paul,MN,US,44.919503,-93.101769,NaN
14637,The Melting Pot,Restaurant,"American, ï¿½ï¿½Vegetarian",1410 Colonial Life Blvd W,29210-7665,Columbia,SC,US,34.028310,-81.092260,NaN
14638,Smoothie King,"American, Smoothies & Juices, Hollywood Restau...",NaN,9439 Sheridan St,33024,Hollywood,FL,US,26.030425,-80.268463,http://smoothieking.com
14639,Buca Di Beppo,"[""Restaurants"",""Banquet Halls & Reception Faci...","[""Mediterranean"",""Restaurants"",""Family Style"",...",801 N Congress Ave,"[""33426""]",Boynton Beach,FL,US,26.535627,-80.090760,http://www.bucadibeppo.com
14640,Grotto Pizza,"Rehoboth Beach Restaurants, Pizza / American /...",NaN,1603 Delaware 1,19971,Rehoboth Beach,DE,US,NaN,NaN,NaN

In [7]:
# Removing [] and "" from the postalCode columns
vegandf['postal_code'] = vegandf['postal_code'].str.strip('[]')
vegandf['postal_code'] = vegandf['postal_code'].str.strip('""')

# Removing Brackets and " from the categories columns and replace , with /
# There are many / replacements inorder to make correct spacings for each category listed.
vegandf['categories'] = vegandf['categories'].str.strip('[]')
vegandf['categories'] = vegandf['categories'].str.strip('""')
vegandf['categories'] = vegandf['categories'].str.replace('","', ',')
vegandf['categories'] = vegandf['categories'].str.replace(',', '/')
vegandf['categories'] = vegandf['categories'].str.replace(' / ', '/')
vegandf['categories'] = vegandf['categories'].str.replace('/ ', '/')
vegandf['categories'] = vegandf['categories'].str.replace('/', ' / ')
vegandf.head()

,name,categories,cuisines,address,postal_code,city,province,country,latitude,longitude,websites
0,Village Inn Restaurant and Bakery,American / American (new) / Clearwater Restaur...,NaN,2871 Gulf To Bay Blvd,33759,Clearwater,FL,US,27.971165,-82.696938,NaN
1,Atlantic No. 5,Caf and Sandwich Place,"Vegetarian, Â Delicatessen",605 W Main St,40202,Louisville,KY,US,38.257020,-85.760013,atlanticno5.com
2,Famous Dave's,American / Barbecue / Puyallup Restaurants / B...,NaN,3803 9th St S W,98373,Puyallup,WA,US,47.154828,-122.303992,http://famousdaves.com
3,The Feve,Coffee & Tea / Restaurant / Restaurants / Bar ...,"Coffee & Tea, Restaurants, American, Â Bar, Â Pu...",30 S Main St,44074,Oberlin,OH,US,41.290823,-82.217640,http://www.thefeve.com
4,Quiznos,Sandwich Place and Fast Food Restaurant,"Take Out Restaurants, Asian Restaurants, Resta...",55 Crescent Dr,94523,Pleasant Hill,CA,US,37.945663,-122.061997,http://www.yallamedi.com/

# Save the dataframes into a new csv

In [8]:
# Save Vegan DF
vegandf.to_csv("Output/vegan_restaurants_cleaned.csv")

# Save Fast Food DF
fastfooddf.to_csv("Output/fast_food_cleaned.csv")

# Begin SQL Alchemy

In [9]:
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine

In [10]:
# Create engine using the `demographics.sqlite` database file
engine = create_engine("sqlite:///Resources/Restaurant_Varieties.sqlite")

# Declare a Base using `automap_base()`
Base = automap_base()

# Use the Base class to reflect the database tables
Base.prepare(engine, reflect=True)

# Print all of the classes mapped to the Base
Base.classes.keys()

DatabaseError: (sqlite3.DatabaseError) file is not a database
[SQL: SELECT name FROM sqlite_master WHERE type='table' ORDER BY name]
(Background on this error at: https://sqlalche.me/e/14/4xp6)